# 是否作为作为守护进程运行, 此时要退出所有进程, 需要向 master 进程发送
# SIGINT 或 SIGTERM 信号
daemon: false

# 进程间通信使用的 unix 域套接字
unix: "/tmp/actor_proxy"

actor_config:
  - actor_name: "echo"
    actor_count: 2
    actor_module: "libsvr_echo.so"
    actor_address: "127.0.0.1"
    actor_port: 7777
    actor_service: "../config/echo.yml"

  - actor_name: "calc"
    actor_count: 2
    actor_module: "libsvr_calc.so"
    actor_address: "127.0.0.1"
    actor_port: 7778
    actor_service: "../config/calc.yml"

  - actor_name: "add"
    actor_count: 1
    actor_module: "libsvr_add.so"
    actor_service: "../config/add.yml"
  
  - actor_name: "step_one"
    actor_count: 1
    actor_module: "libsvr_step_one.so"
    actor_service: "../config/step_one.yml"

  - actor_name: "step_two"
    actor_count: 1
    actor_module: "libsvr_step_two.so"
    actor_service: "../config/step_two.yml"

  - actor_name: "use_thread"
    actor_count: 1
    actor_module: "libsvr_use_thread.so"
    actor_address: "127.0.0.1"
    actor_port: 7779
    actor_service: "../config/use_thread.yml"

  - actor_name: "use_sqlite"
    actor_count: 2
    actor_module: "libsvr_use_sqlite.so"
    actor_address: "127.0.0.1"
    actor_port: 7780
    actor_service: "../config/use_sqlite.yml"